In [10]:
import numpy as np

# X = (hours sleeping, hours studying), y = score on test
X = np.array(([2, 9,3], [1, 5,10], [3, 6, 11]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) # maximum of X array
y = y/100 # max test score is 100

class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 3
        self.outputSize = 1
        self.hiddenSize = 5

        #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        #forward propagation through our network
        self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
        o = self.sigmoid(self.z3) # final activation function
        return o 

    def sigmoid(self, s):
        # activation function 
        return 1/(1+np.exp(-s))

    def sigmoidPrime(self, s):
        #derivative of sigmoid
        return s * (1 - s)

    def backward(self, X, y, o):
        # backward propgate through the network
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
    def train (self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)



In [11]:
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    print ("Input: \n " + str(X)) 
    print ("Actual Output: \n" + str(y)) 
    print ("Predicted Output: \n" + str(NN.forward(X))) 
    print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
    print ("\n")
    NN.train(X, y)

Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.59199798]
 [0.61203762]
 [0.62378986]]
Loss: 
0.07997950228178087


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.65255443]
 [0.67442431]
 [0.68484523]]
Loss: 
0.04935131636388535


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.69432302]
 [0.71657695]
 [0.72602613]]
Loss: 
0.03279589946257032


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.72432527]
 [0.74632894]
 [0.75511031]]
Loss: 
0.02313497970324027




 [0.8942253 ]]
Loss: 
0.0005378563543523896


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88969791]
 [0.88596683]
 [0.89420823]]
Loss: 
0.0005367340179551989


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88972919]
 [0.88594138]
 [0.89419121]]
Loss: 
0.0005356143688587649


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88976044]
 [0.88591596]
 [0.89417422]]
Loss: 
0.0005344973982536955


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.88979165]
 [0.88

 [0.89193401]]
Loss: 
0.00038591857684070765


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89435529]
 [0.88222775]
 [0.89192246]]
Loss: 
0.0003851399237375554


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8943817 ]
 [0.88220675]
 [0.89191094]]
Loss: 
0.00038436293710874836


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89440808]
 [0.88218578]
 [0.89189945]]
Loss: 
0.0003835876125358575


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89443444]
 [0.

Loss: 
0.0002652518847457919


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89886845]
 [0.87864372]
 [0.89019229]]
Loss: 
0.00026472258084243963


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89889046]
 [0.87862622]
 [0.89018505]]
Loss: 
0.00026419433758546326


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89891244]
 [0.87860872]
 [0.89017783]]
Loss: 
0.0002636671526222238


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8989344 ]
 [0.87859124]
 [0.8

Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90248924]
 [0.87574434]
 [0.88916184]]
Loss: 
0.00018507113703506285


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90250778]
 [0.87572938]
 [0.88915741]]
Loss: 
0.00018470043703420027


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90252629]
 [0.87571443]
 [0.889153  ]]
Loss: 
0.00018433046334268705


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90254479]
 [0.8756995 ]
 [0.88914861]]
Loss: 
0.00018396121

Loss: 
0.00012442070646697057


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.9058297 ]
 [0.87301894]
 [0.88851145]]
Loss: 
0.00012416865735144714


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90584498]
 [0.87300631]
 [0.88850917]]
Loss: 
0.00012391710200134102


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90586025]
 [0.8729937 ]
 [0.8885069 ]]
Loss: 
0.0001236660394681616


Input: 
 [[0.66666667 1.         0.27272727]
 [0.33333333 0.55555556 0.90909091]
 [1.         0.66666667 1.        ]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.90587551]
 [0.8729811 ]
 [0.