In [25]:
import numpy as np


## code to insert the 1st matrix

m=input('please insert the number of raws for the 1st matrix = ')
n=input('Please input the number or coloum of the 1st matrix = ')

Mat1=[]
for i in range(0,m):
    Mat1.append([])
    for j in range(0,n):
        print('insert ', i+1, 'row & ', j+1, ' column')
        x=input()
        Mat1[i].append(x)
Mat1=np.array(Mat1)
print(Mat1)
        

please insert the number of raws for the 1st matrix = 2
Please input the number or coloum of the 1st matrix = 2
('insert ', 1, 'row & ', 1, ' column')
1
('insert ', 1, 'row & ', 2, ' column')
2
('insert ', 2, 'row & ', 1, ' column')
3
('insert ', 2, 'row & ', 2, ' column')
4
[[1 2]
 [3 4]]


In [26]:
p=input('please input the row of the 2nd matrix')
q=input('please input the coloumn of the 2nd matrix')
Mat2=[]
for i in range(0,p):
    Mat2.append([])
    for j in range(0,q):
        print('insert ''insert ', i+1, 'row & ', j+1, ' column')
        y=input()
        Mat2[i].append(y)
Mat2=np.array(Mat2)
print(Mat2)
        


please input the row of the 2nd matrix2
please input the coloumn of the 2nd matrix2
('insert insert ', 1, 'row & ', 1, ' column')
1
('insert insert ', 1, 'row & ', 2, ' column')
2
('insert insert ', 2, 'row & ', 1, ' column')
3
('insert insert ', 2, 'row & ', 2, ' column')
4
[[1 2]
 [3 4]]


In [29]:
z=0
Mul=[]
for i in range(0,m):
    Mul.append([])
    for j in range(0,q):
        for k in range(0,p):
            z=z+(Mat1[i,k]*Mat2[k,j])
        Mul[i].append(z)
        z=0
Mul=np.array(Mul)
print(Mul)
        
            

[[ 7 10]
 [15 22]]
