In [7]:
import numpy as np

n=input('Please input the number of row of the 1st matrix = ')
m=input('Please input the number of column of the 1st matrix = ')

## Here is the code for inseting the 1st matrix

mat1=[]
for i in range(0,n):
    mat1.append([])
    for j in range(0,m):
        print('insert',i+1, 'row & ', j+1, 'coulmn')
        x=input()
        mat1[i].append(x)
mat1=np.array(mat1)
print(mat1)

## Here is the code for the 2nd Matrix

p=input('Please input the row of the 2nd matrix')
q=input('Please input the column of the 2nd matrix')
mat2=[]
for i in range(0,p):
    mat2.append([])
    for j in range(0,q):
        print('insert',i+1,'row and ', j+1, 'coulmn')
        y=input()
        mat2[i].append(y)
mat2=np.array(mat2)
print(mat2)


## Here is the code for the matrix multiplication
z=0
mul=[]
for i in range(0,m):
    mul.append([])
    for j in range(0,q):
        for k in range(0,p):
            z=z+(mat1[i,k]*mat2[k,j])
        mul[i].append(z)
        z=0
mul=np.array(mul)
print(mul)
            



Please input the number of row of the 1st matrix = 2
Please input the number of column of the 1st matrix = 2
('insert', 1, 'row & ', 1, 'coulmn')
1
('insert', 1, 'row & ', 2, 'coulmn')
2
('insert', 2, 'row & ', 1, 'coulmn')
3
('insert', 2, 'row & ', 2, 'coulmn')
4
[[1 2]
 [3 4]]
Please input the row of the 2nd matrix2
Please input the column of the 2nd matrix2
('insert', 1, 'row and ', 1, 'coulmn')
1
('insert', 1, 'row and ', 2, 'coulmn')
2
('insert', 2, 'row and ', 1, 'coulmn')
3
('insert', 2, 'row and ', 2, 'coulmn')
4
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]


In [5]:
print mat2

[[1 2]
 [3 4]]
