# matrix multiplication algorithm

Here we will try to understand the fundamental concept of matrix multiplication. For that let us consider two matrices x and y.

In [ ]:
x = [[1,2,3],[3,4,6],[7,8,9]]

In [24]:
y = [[5,6,8],[7,8,10],[2,3,9]]

Now we will convert these arrays into matrices

In [25]:
import numpy as np

In [26]:
x = np.array(x)

In [27]:
y = np.array(y)

In [28]:
[I,J] = x.shape

In [29]:
[K,H] = y.shape

In [30]:
z = np.zeros((I,H))

In [31]:
for i in range(I):
    for j in range(H):
        for k in range(K):
            
            z[i,j] += x[i,k]*y[k,j]
print z

[[  25.   31.   55.]
 [  55.   68.  118.]
 [ 109.  133.  217.]]


You can check performance of your algorithm by inbuild **"dot"** function of numpy library 

In [21]:
np.dot(x,y)

array([[ 25,  31,  55],
       [ 55,  68, 118],
       [109, 133, 217]])